apiVersion: v1
kind: Service
metadata:
  name: stop-collector-server
  namespace: atlas
spec:
  selector:
    app: stop-collector-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
